image:
  name: pintos-base
  pull_policy: never

stages:
  - build
  - test

# Build the PintOS utils
build-pintos:
  stage: build
  script:
    - cd src/utils
    - make
    - cd ../../
    - echo "export PATH=\$PATH:$(pwd)/src/utils" > .env
  artifacts:
    paths:
      - src/utils # Save the compiled PintOS utils
      - .env      # Save the environment file
  rules:
    # Run this job when there is an open MR to master or on commits to branches with an open MR to master
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
      allow_failure: false
  tags:
    - pintos-runner

# Run the tests for task 3 - Always passes for now
test-task-3:
  stage: test
  dependencies:
    - build-pintos
  script:
    - source .env    # Load the environment variables
    - cd src/vm
    - make
    - cd build
    - make check #| tee check_output.log
#    - if grep -q "FAIL" check_output.log; then echo "Failure."; exit 1; fi
  rules:
    # Run this job when there is an open MR to master or on commits to branches with an open MR to master
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
      allow_failure: false
  resource_group: test-tasks
  tags:
    - pintos-runner

# Run the tests for task 2
test-task-2:
  stage: test
  dependencies:
    - build-pintos
  script:
    - source .env    # Load the environment variables
    - cd src/userprog
    - make
    - cd build
    - make check | tee check_output.log
    - if grep -q "FAIL" check_output.log; then echo "Failure."; exit 1; fi
  rules:
    # Run this job when there is an open MR to master or on commits to branches with an open MR to master
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  resource_group: test-tasks
  tags:
    - pintos-runner
  when:
    manual

# Run the tests for task 1
test-task-1:
  stage: test
  dependencies:
    - build-pintos
  script:
    - source .env    # Load the environment variables
    - cd src/threads
    - make
    - cd build
    - make check | tee check_output.log
    - if grep -q "FAIL" check_output.log; then echo "Failure."; exit 1; fi
  rules:
    # Run this job when there is an open MR to master or on commits to branches with an open MR to master
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  resource_group: test-tasks
  tags:
    - pintos-runner
  when:
    manual

# Run the tests for task 0
test-task-0:
  stage: test
  dependencies:
    - build-pintos
  script:
    - source .env    # Load the environment variables
    - cd src/devices
    - make
    - cd build
    - make check | tee check_output.log
    - if grep -q "FAIL" check_output.log; then echo "Failure."; exit 1; fi
  rules:
    # Run this job when there is an open MR to master or on commits to branches with an open MR to master
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  resource_group: test-tasks
  tags:
    - pintos-runner
  when:
    manual
